/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIS;
public class VentanaPrincipalProfesor extends javax.swing.JFrame {
    public VentanaPrincipalProfesor() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Ventana principal Profesor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jButtonRegistrarPlanCurso = new javax.swing.JButton();
        jButtonModificarPlanDeCurso = new javax.swing.JButton();
        jButtonRegistrarAvanceCurso = new javax.swing.JButton();
        jButtonSolicitarModificaciónDePlan = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelTitulo.setText("Profesor");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jButtonRegistrarPlanCurso.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonRegistrarPlanCurso.setText("<html><center>Registrar Plan de Curso");
        getContentPane().add(jButtonRegistrarPlanCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 200, 70));

        jButtonModificarPlanDeCurso.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonModificarPlanDeCurso.setText("<html><center>Modificar Plan deCurso");
        getContentPane().add(jButtonModificarPlanDeCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 200, 70));

        jButtonRegistrarAvanceCurso.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonRegistrarAvanceCurso.setText("<html><center>Registrar Avance De Curso");
        getContentPane().add(jButtonRegistrarAvanceCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 200, 70));

        jButtonSolicitarModificaciónDePlan.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonSolicitarModificaciónDePlan.setText("<html><center>Solicitar Modificación Del Plan");
        getContentPane().add(jButtonSolicitarModificaciónDePlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 200, 70));

        jButtonCerrarSesion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonCerrarSesion.setText("Cerrar Sesión");
        getContentPane().add(jButtonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonModificarPlanDeCurso;
    private javax.swing.JButton jButtonRegistrarAvanceCurso;
    private javax.swing.JButton jButtonRegistrarPlanCurso;
    private javax.swing.JButton jButtonSolicitarModificaciónDePlan;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
